version: '3.8'
services:
  prod:
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports:
      - "5432:5432"
  test:
    build:
      context: .
      dockerfile: test.Dockerfile
    ports:
      - "5432::5432"