name: Postgres CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build test docker image
        run: docker build . --file test.Dockerfile --tag ${{ github.repository }}:latest-test

      - name: Build prod docker image
        run: docker build . --file prod.Dockerfile --tag ${{ github.repository }}:latest
