name: Postgres CICD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.55.0
        id: tag-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: minor
          RELEASE_BRANCHES: master

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build test docker image
        run: docker build . --file test.Dockerfile --tag ${{ github.repository }}:${{ steps.tag-version.outputs.new_tag }}-test --tag ${{ github.repository }}:latest-test

      - name: Push versioned test docker image
        run: docker push ${{ github.repository }}:${{ steps.tag-version.outputs.new_tag }}-test

      - name: Push latest test docker image
        run: docker push ${{ github.repository }}:latest-test

      - name: Build prod docker image
        run: docker build . --file prod.Dockerfile --tag ${{ github.repository }}:${{ steps.tag-version.outputs.new_tag }} --tag ${{ github.repository }}:latest

      - name: Push versioned prod docker image
        run: docker push ${{ github.repository }}:${{ steps.tag-version.outputs.new_tag }}

      - name: Push latest prod docker image
        run: docker push ${{ github.repository }}:latest
